"""'add app capabilities'

Revision ID: ed9f015280d3
Revises: 11a81b5bc6c5
Create Date: 2026-08-27 22:54:52.423863

"""

import sqlalchemy as sa
from alembic import op

import mealie.db.migration_types

# revision identifiers, used by Alembic.
revision = "ed9f015280d3"
down_revision: str | None = "11a81b5bc6c5"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # Migrations run before Mealie creates its default user. An empty users table
    # therefore identifies a fresh Hearth installation, while any existing user
    # identifies an upgraded Mealie installation whose legacy features must stay on.
    legacy_features = bool(op.get_bind().execute(sa.text("SELECT COUNT(*) FROM users")).scalar_one())

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_capabilities",
        sa.Column("guides", sa.Boolean(), nullable=False),
        sa.Column("legacy_recipes", sa.Boolean(), nullable=False),
        sa.Column("meal_planning", sa.Boolean(), nullable=False),
        sa.Column("shopping_lists", sa.Boolean(), nullable=False),
        sa.Column("nutrition", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("app_capabilities", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_app_capabilities_created_at"), ["created_at"], unique=False)

    capabilities_table = sa.table(
        "app_capabilities",
        sa.column("id", sa.Integer()),
        sa.column("guides", sa.Boolean()),
        sa.column("legacy_recipes", sa.Boolean()),
        sa.column("meal_planning", sa.Boolean()),
        sa.column("shopping_lists", sa.Boolean()),
        sa.column("nutrition", sa.Boolean()),
    )
    op.bulk_insert(
        capabilities_table,
        [
            {
                "id": 1,
                "guides": True,
                "legacy_recipes": legacy_features,
                "meal_planning": legacy_features,
                "shopping_lists": legacy_features,
                "nutrition": legacy_features,
            }
        ],
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_capabilities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_app_capabilities_created_at"))

    op.drop_table("app_capabilities")
    # ### end Alembic commands ###
