"""'add guide frequency requirements and tips'

Revision ID: de0599e50a71
Revises: e5564b5892ae
Create Date: 2026-08-26 15:57:59.588516

"""

import sqlalchemy as sa
from alembic import op

import mealie.db.migration_types

# revision identifiers, used by Alembic.
revision = "de0599e50a71"
down_revision: str | None = "e5564b5892ae"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guide_requirements",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("guide_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.CheckConstraint("kind IN ('tool', 'material')", name="guide_requirement_kind_check"),
        sa.ForeignKeyConstraint(["guide_id"], ["guides.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("guide_requirements", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_guide_requirements_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_guide_requirements_guide_id"), ["guide_id"], unique=False)

    with op.batch_alter_table("guide_steps", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tip", sa.Text(), nullable=True))

    with op.batch_alter_table("guides", schema=None) as batch_op:
        batch_op.add_column(sa.Column("frequency", sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f("ix_guides_frequency"), ["frequency"], unique=False)
        batch_op.create_check_constraint(
            "guide_frequency_check",
            "frequency IS NULL OR frequency IN ('one_time', 'weekly', 'monthly', 'yearly', 'as_needed')",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("guides", schema=None) as batch_op:
        batch_op.drop_constraint("guide_frequency_check", type_="check")
        batch_op.drop_index(batch_op.f("ix_guides_frequency"))
        batch_op.drop_column("frequency")

    with op.batch_alter_table("guide_steps", schema=None) as batch_op:
        batch_op.drop_column("tip")

    with op.batch_alter_table("guide_requirements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_guide_requirements_guide_id"))
        batch_op.drop_index(batch_op.f("ix_guide_requirements_created_at"))

    op.drop_table("guide_requirements")
    # ### end Alembic commands ###
