"""'add guide media'

Revision ID: f5ba4484ce44
Revises: de0599e50a71
Create Date: 2026-08-27 14:10:45.821847

"""

import sqlalchemy as sa
from alembic import op

import mealie.db.migration_types

# revision identifiers, used by Alembic.
revision = "f5ba4484ce44"
down_revision: str | None = "de0599e50a71"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guide_step_images",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("step_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("caption", sa.String(length=1000), nullable=True),
        sa.Column("alt_text", sa.String(length=500), nullable=True),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(["step_id"], ["guide_steps.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("guide_step_images", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_guide_step_images_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_guide_step_images_step_id"), ["step_id"], unique=False)

    with op.batch_alter_table("guides", schema=None) as batch_op:
        batch_op.add_column(sa.Column("cover_image_version", sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("guides", schema=None) as batch_op:
        batch_op.drop_column("cover_image_version")

    with op.batch_alter_table("guide_step_images", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_guide_step_images_step_id"))
        batch_op.drop_index(batch_op.f("ix_guide_step_images_created_at"))

    op.drop_table("guide_step_images")
    # ### end Alembic commands ###
