"""'add guides'

Revision ID: 39ee4257d98e
Revises: 2187537c52b8
Create Date: 2026-08-25 10:42:23.138854

"""

import sqlalchemy as sa
from alembic import op

import mealie.db.migration_types

# revision identifiers, used by Alembic.
revision = "39ee4257d98e"
down_revision: str | None = "2187537c52b8"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guides",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("group_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("household_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("author_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("title_normalized", sa.String(), nullable=False),
        sa.Column("description_normalized", sa.String(), nullable=False),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug", "group_id", name="guide_slug_group_id_key"),
    )
    with op.batch_alter_table("guides", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_guides_author_id"), ["author_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_guides_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_guides_description_normalized"), ["description_normalized"], unique=False)
        batch_op.create_index(batch_op.f("ix_guides_group_id"), ["group_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_guides_household_id"), ["household_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_guides_slug"), ["slug"], unique=False)
        batch_op.create_index(batch_op.f("ix_guides_title_normalized"), ["title_normalized"], unique=False)

    op.create_table(
        "guide_steps",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("guide_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(["guide_id"], ["guides.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("guide_steps", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_guide_steps_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_guide_steps_guide_id"), ["guide_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("guide_steps", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_guide_steps_guide_id"))
        batch_op.drop_index(batch_op.f("ix_guide_steps_created_at"))

    op.drop_table("guide_steps")
    with op.batch_alter_table("guides", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_guides_title_normalized"))
        batch_op.drop_index(batch_op.f("ix_guides_slug"))
        batch_op.drop_index(batch_op.f("ix_guides_household_id"))
        batch_op.drop_index(batch_op.f("ix_guides_group_id"))
        batch_op.drop_index(batch_op.f("ix_guides_description_normalized"))
        batch_op.drop_index(batch_op.f("ix_guides_created_at"))
        batch_op.drop_index(batch_op.f("ix_guides_author_id"))

    op.drop_table("guides")
    # ### end Alembic commands ###
