"""'add guide classification and safety'

Revision ID: e5564b5892ae
Revises: 39ee4257d98e
Create Date: 2026-08-26 11:26:02.799192

"""

import sqlalchemy as sa
from alembic import op
from text_unidecode import unidecode

import mealie.db.migration_types

# revision identifiers, used by Alembic.
revision = "e5564b5892ae"
down_revision: str | None = "39ee4257d98e"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guide_categories",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("group_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("normalized_name", sa.String(length=100), nullable=False),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", "normalized_name", name="guide_category_group_name_key"),
    )
    with op.batch_alter_table("guide_categories", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_guide_categories_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_guide_categories_group_id"), ["group_id"], unique=False)

    op.create_table(
        "guide_tags",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("group_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("normalized_name", sa.String(length=50), nullable=False),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", "normalized_name", name="guide_tag_group_name_key"),
    )
    with op.batch_alter_table("guide_tags", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_guide_tags_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_guide_tags_group_id"), ["group_id"], unique=False)

    op.create_table(
        "guide_callouts",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("guide_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.CheckConstraint("kind IN ('warning', 'avoid')", name="guide_callout_kind_check"),
        sa.ForeignKeyConstraint(["guide_id"], ["guides.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("guide_callouts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_guide_callouts_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_guide_callouts_guide_id"), ["guide_id"], unique=False)

    op.create_table(
        "guides_to_tags",
        sa.Column("guide_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("tag_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.ForeignKeyConstraint(["guide_id"], ["guides.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["guide_tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("guide_id", "tag_id"),
    )
    with op.batch_alter_table("guides", schema=None) as batch_op:
        batch_op.add_column(sa.Column("category_id", mealie.db.migration_types.GUID(), nullable=True))
        batch_op.add_column(sa.Column("guide_type", sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column("difficulty", sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column("preparation_minutes", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("execution_minutes", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("search_document_normalized", sa.Text(), server_default=sa.text("''"), nullable=False)
        )
        batch_op.create_index(batch_op.f("ix_guides_category_id"), ["category_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_guides_difficulty"), ["difficulty"], unique=False)
        batch_op.create_index(batch_op.f("ix_guides_guide_type"), ["guide_type"], unique=False)
        batch_op.create_foreign_key(
            "fk_guides_category_id_guide_categories",
            "guide_categories",
            ["category_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_check_constraint(
            "guide_difficulty_check", "difficulty IS NULL OR difficulty IN ('beginner', 'intermediate', 'advanced')"
        )

    connection = op.get_bind()
    guides = connection.execute(sa.text("SELECT id, title_normalized, description_normalized FROM guides")).mappings()
    for guide in guides:
        step_text = connection.execute(
            sa.text("SELECT text FROM guide_steps WHERE guide_id = :guide_id ORDER BY position"),
            {"guide_id": guide["id"]},
        ).scalars()
        search_document = " ".join(
            unidecode(part).lower().strip()
            for part in [guide["title_normalized"], guide["description_normalized"], *step_text]
            if part
        )
        connection.execute(
            sa.text("UPDATE guides SET search_document_normalized = :document WHERE id = :guide_id"),
            {"document": search_document, "guide_id": guide["id"]},
        )

    with op.batch_alter_table("guides", schema=None) as batch_op:
        batch_op.alter_column(
            "search_document_normalized", existing_type=sa.Text(), server_default=None, existing_nullable=False
        )
        batch_op.create_check_constraint(
            "guide_execution_minutes_check", "execution_minutes IS NULL OR execution_minutes >= 0"
        )
        batch_op.create_check_constraint(
            "guide_preparation_minutes_check", "preparation_minutes IS NULL OR preparation_minutes >= 0"
        )
        batch_op.create_check_constraint(
            "guide_type_check",
            "guide_type IS NULL OR guide_type IN ('cleaning', 'maintenance', 'setup', 'emergency', 'troubleshooting', 'care_instructions')",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("guides", schema=None) as batch_op:
        batch_op.drop_constraint("guide_type_check", type_="check")
        batch_op.drop_constraint("guide_preparation_minutes_check", type_="check")
        batch_op.drop_constraint("guide_execution_minutes_check", type_="check")
        batch_op.drop_constraint("guide_difficulty_check", type_="check")
        batch_op.drop_constraint("fk_guides_category_id_guide_categories", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_guides_guide_type"))
        batch_op.drop_index(batch_op.f("ix_guides_difficulty"))
        batch_op.drop_index(batch_op.f("ix_guides_category_id"))
        batch_op.drop_column("search_document_normalized")
        batch_op.drop_column("execution_minutes")
        batch_op.drop_column("preparation_minutes")
        batch_op.drop_column("difficulty")
        batch_op.drop_column("guide_type")
        batch_op.drop_column("category_id")

    op.drop_table("guides_to_tags")
    with op.batch_alter_table("guide_callouts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_guide_callouts_guide_id"))
        batch_op.drop_index(batch_op.f("ix_guide_callouts_created_at"))

    op.drop_table("guide_callouts")
    with op.batch_alter_table("guide_tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_guide_tags_group_id"))
        batch_op.drop_index(batch_op.f("ix_guide_tags_created_at"))

    op.drop_table("guide_tags")
    with op.batch_alter_table("guide_categories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_guide_categories_group_id"))
        batch_op.drop_index(batch_op.f("ix_guide_categories_created_at"))

    op.drop_table("guide_categories")
    # ### end Alembic commands ###
