"""'add guide knowledge metadata'

Revision ID: 11a81b5bc6c5
Revises: f5ba4484ce44
Create Date: 2026-08-27 15:49:15.019942

"""

import sqlalchemy as sa
from alembic import op

import mealie.db.migration_types

# revision identifiers, used by Alembic.
revision = "11a81b5bc6c5"
down_revision: str | None = "f5ba4484ce44"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guide_relations",
        sa.Column("guide_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("related_guide_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.CheckConstraint("guide_id != related_guide_id", name="guide_relation_not_self_check"),
        sa.ForeignKeyConstraint(["guide_id"], ["guides.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["related_guide_id"], ["guides.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("guide_id", "related_guide_id"),
    )
    op.create_table(
        "guide_sources",
        sa.Column("id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("guide_id", mealie.db.migration_types.GUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("url", sa.String(length=2000), nullable=False),
        sa.Column("created_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", mealie.db.migration_types.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(["guide_id"], ["guides.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("guide_sources", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_guide_sources_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_guide_sources_guide_id"), ["guide_id"], unique=False)

    with op.batch_alter_table("guides", schema=None) as batch_op:
        batch_op.add_column(sa.Column("notes", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("last_reviewed", sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f("ix_guides_last_reviewed"), ["last_reviewed"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("guides", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_guides_last_reviewed"))
        batch_op.drop_column("last_reviewed")
        batch_op.drop_column("notes")

    with op.batch_alter_table("guide_sources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_guide_sources_guide_id"))
        batch_op.drop_index(batch_op.f("ix_guide_sources_created_at"))

    op.drop_table("guide_sources")
    op.drop_table("guide_relations")
    # ### end Alembic commands ###
